version: "3"
services:
  test:
    build: .
    ports:
      - "3050"
    container_name: high-res-test
    environment:
      PORT: 3050
      NODE_PATH: app/src
      NODE_ENV: test
      GATEWAY_URL: http://mymachine:9000
      MICROSERVICE_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
      LOCAL_URL: http://mymachine:3055
      FASTLY_ENABLED: "false"
      AWS_REGION: "us-east-1"
      REQUIRE_API_KEY: true
      AWS_ACCESS_KEY_ID: "test"
      AWS_SECRET_ACCESS_KEY: "test"
    command: test
