version: "3"
services:
  develop:
    build: .
    ports:
      - "3051:3051"
    container_name: high-res
    environment:
      PORT: 3051
      NODE_PATH: app/src
      GATEWAY_URL: http://mymachine:9000
      LOCAL_URL: http://mymachine:3051
      MICROSERVICE_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
      SENTINEL_KEY: <key>
      LANDSAT_KEY: <key>
      FASTLY_ENABLED: "false"
      AWS_REGION: "us-east-1"
      REQUIRE_API_KEY: true
      AWS_ACCESS_KEY_ID: "test"
      AWS_SECRET_ACCESS_KEY: "test"
    command: develop
    volumes:
      - ./app:/opt/high-res/app
