apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: gfw
  name: high-res
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: high-res
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
